// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import "../src/SkillSealRegistry.sol";
import "../src/SkillSealSettlement.sol";
import "../src/MockUSDT.sol";

contract SkillSealProtocolTest is Test {
    SkillSealRegistry registry; SkillSealSettlement settlement; MockUSDT token;
    address operator = makeAddr("operator"); address attacker = makeAddr("attacker"); address agent = makeAddr("agent"); address provider = makeAddr("provider"); address assessor = makeAddr("assessor");
    bytes32 tool = keccak256("mercury-fx"); bytes32 v4 = keccak256("v4"); bytes32 v5 = keccak256("v5"); bytes32 mandate = keccak256("treasury"); bytes32 assessment = keccak256("assessment");

    function setUp() public { registry = new SkillSealRegistry(address(this), assessor); token = new MockUSDT(agent, 10_000_000); settlement = new SkillSealSettlement(address(registry), address(token)); vm.prank(operator); registry.registerTool(tool); vm.prank(operator); registry.publishVersion(tool, v4, provider); vm.prank(assessor); registry.issueSeal(tool, 1, v4, assessment, SkillSealRegistry.Risk.LOW, uint64(block.timestamp + 3 days)); vm.prank(agent); registry.registerMandate(mandate, keccak256("policy"), SkillSealRegistry.Risk.MEDIUM, 50_000, 100_000); vm.prank(agent); token.approve(address(settlement), type(uint256).max); }

    function testRegisterRejectsZeroAndDuplicate() public { vm.expectRevert(SkillSealRegistry.ZeroValue.selector); registry.registerTool(bytes32(0)); vm.prank(operator); vm.expectRevert(SkillSealRegistry.AlreadyExists.selector); registry.registerTool(tool); }
    function testAttackerCannotPublishOperatorVersion() public { vm.prank(attacker); vm.expectRevert(SkillSealRegistry.Unauthorized.selector); registry.publishVersion(tool, v5, provider); }
    function testFuzzAttackerNeverPublishes(address arbitraryAttacker) public { vm.assume(arbitraryAttacker != operator && arbitraryAttacker != address(0)); vm.prank(arbitraryAttacker); vm.expectRevert(SkillSealRegistry.Unauthorized.selector); registry.publishVersion(tool, v5, provider); }
    function testHistoricalVersionsRemainImmutable() public { (bytes32 originalDigest, address originalRecipient,, bool exists) = registry.versions(tool, 1); vm.prank(operator); registry.publishVersion(tool, v5, attacker); (bytes32 afterDigest, address afterRecipient,, bool stillExists) = registry.versions(tool, 1); assertEq(originalDigest, v4); assertEq(afterDigest, v4); assertEq(originalRecipient, provider); assertEq(afterRecipient, provider); assertTrue(exists && stillExists); }
    function testOnlyAssessorIssuesAndSealMustBindCurrentDigest() public { vm.prank(attacker); vm.expectRevert(); registry.issueSeal(tool, 1, v4, assessment, SkillSealRegistry.Risk.LOW, uint64(block.timestamp + 1 days)); vm.prank(assessor); vm.expectRevert(SkillSealRegistry.InvalidState.selector); registry.issueSeal(tool, 1, v4, assessment, SkillSealRegistry.Risk.LOW, uint64(block.timestamp + 1 days)); vm.prank(assessor); vm.expectRevert(SkillSealRegistry.InvalidState.selector); registry.issueSeal(tool, 1, v5, assessment, SkillSealRegistry.Risk.LOW, uint64(block.timestamp + 1 days)); vm.prank(assessor); vm.expectRevert(SkillSealRegistry.InvalidState.selector); registry.issueSeal(tool, 2, v4, assessment, SkillSealRegistry.Risk.LOW, uint64(block.timestamp + 1 days)); }
    function testExpiredAndRevokedSealsBlockSettlement() public { vm.warp(block.timestamp + 3 days + 1); vm.prank(agent); vm.expectRevert(SkillSealRegistry.InvalidState.selector); settlement.settleInvocation(keccak256("expired"), tool, mandate, 1, v4, 1); vm.prank(assessor); registry.revokeSeal(tool, 1); vm.prank(agent); vm.expectRevert(SkillSealRegistry.InvalidState.selector); settlement.settleInvocation(keccak256("revoked"), tool, mandate, 1, v4, 1); }
    function testHistoricalSealBecomesStaleAfterVersionUpdate() public { vm.prank(operator); registry.publishVersion(tool, v5, provider); vm.prank(agent); vm.expectRevert(SkillSealRegistry.InvalidState.selector); settlement.settleInvocation(keccak256("old"), tool, mandate, 1, v4, 20_000); }
    function testFuzzSealForDigestACannotAuthorizeDigestB(bytes32 otherDigest) public { vm.assume(otherDigest != v4 && otherDigest != bytes32(0)); vm.prank(agent); vm.expectRevert(SkillSealRegistry.InvalidState.selector); settlement.settleInvocation(keccak256(abi.encode(otherDigest)), tool, mandate, 1, otherDigest, 1); }
    function testMandateOwnershipAndDuplicateRegistration() public { vm.prank(attacker); vm.expectRevert(SkillSealRegistry.InvalidState.selector); settlement.settleInvocation(keccak256("owner"), tool, mandate, 1, v4, 1); vm.prank(agent); vm.expectRevert(SkillSealRegistry.AlreadyExists.selector); registry.registerMandate(mandate, keccak256("policy"), SkillSealRegistry.Risk.MEDIUM, 50_000, 100_000); }
    function testFuzzAmountOverInvocationCapAlwaysFails(uint128 amount) public { vm.assume(amount > 50_000); vm.prank(agent); vm.expectRevert(SkillSealRegistry.InvalidState.selector); settlement.settleInvocation(keccak256(abi.encode(amount)), tool, mandate, 1, v4, amount); }
    function testDailyCapEpochResetAndReceiptReplay() public { vm.prank(agent); settlement.settleInvocation(keccak256("one"), tool, mandate, 1, v4, 50_000); vm.prank(agent); settlement.settleInvocation(keccak256("two"), tool, mandate, 1, v4, 50_000); vm.prank(agent); vm.expectRevert(SkillSealSettlement.DailyCapExceeded.selector); settlement.settleInvocation(keccak256("three"), tool, mandate, 1, v4, 1); vm.prank(agent); vm.expectRevert(SkillSealSettlement.ReceiptUsed.selector); settlement.settleInvocation(keccak256("one"), tool, mandate, 1, v4, 1); vm.warp(block.timestamp + 1 days); vm.prank(agent); settlement.settleInvocation(keccak256("next-epoch"), tool, mandate, 1, v4, 50_000); }
    function testFuzzDailySpendNeverExceedsCap(uint128 first, uint128 second) public { first = uint128(bound(first, 1, 50_000)); second = uint128(bound(second, 1, 50_000)); vm.prank(agent); settlement.settleInvocation(keccak256("fuzz-first"), tool, mandate, 1, v4, first); if (uint256(first) + second <= 100_000) { vm.prank(agent); settlement.settleInvocation(keccak256("fuzz-second"), tool, mandate, 1, v4, second); } else { vm.prank(agent); vm.expectRevert(SkillSealSettlement.DailyCapExceeded.selector); settlement.settleInvocation(keccak256("fuzz-second"), tool, mandate, 1, v4, second); } assertLe(settlement.spentByEpoch(mandate, block.timestamp / 1 days), 100_000); }
    function testRecipientIsVersionBoundAndTokenTransferExact() public { uint256 beforeProvider = token.balanceOf(provider); uint256 beforeAgent = token.balanceOf(agent); vm.prank(agent); settlement.settleInvocation(keccak256("bound"), tool, mandate, 1, v4, 20_000); assertEq(token.balanceOf(provider), beforeProvider + 20_000); assertEq(token.balanceOf(agent), beforeAgent - 20_000); assertEq(token.balanceOf(attacker), 0); }
    function testBondCooldownAndSingleWithdrawal() public { vm.deal(operator, 1 ether); vm.prank(operator); registry.depositBond{value: 1 ether}(); vm.prank(operator); registry.requestBondWithdrawal(1 ether); vm.prank(operator); vm.expectRevert(SkillSealRegistry.InvalidState.selector); registry.withdrawBond(); vm.warp(block.timestamp + registry.BOND_COOLDOWN()); uint256 beforeBalance = operator.balance; vm.prank(operator); registry.withdrawBond(); assertEq(operator.balance, beforeBalance + 1 ether); vm.prank(operator); vm.expectRevert(SkillSealRegistry.InvalidState.selector); registry.withdrawBond(); }
}
