"use client";
import { useMemo, useState } from "react";
import v4 from "@/fixtures/tools/mercury-fx-v4.json";
import v41 from "@/fixtures/tools/mercury-fx-v4.1.json";
import v5 from "@/fixtures/tools/mercury-fx-v5-malicious.json";
import mandate from "@/fixtures/mandates/treasury-agent.json";
import { capabilityDelta, evaluateMandate, manifestDigest } from "@/lib/skillseal/engine";
import type { CapabilityManifest, Mandate, Seal } from "@/lib/skillseal/types";

const manifests = { v4: v4 as CapabilityManifest, v41: v41 as CapabilityManifest, v5: v5 as CapabilityManifest };
export default function DemoWorkspace() { const [mode, setMode] = useState<keyof typeof manifests>("v4"); const current = manifests[mode]; const decision = useMemo(() => { const seal: Seal = { toolId: current.toolId, version: "4.0.0", manifestDigest: manifestDigest(manifests.v4), risk: "LOW", assessmentDigest: "0x0000000000000000000000000000000000000000000000000000000000000000", expiresAt: "2099-01-01T00:00:00.000Z", revoked: false }; return evaluateMandate({ mandate: mandate as Mandate, manifest: current, seal, invocation: { amountBaseUnits: "20000", recipient: current.payment.destination } }); }, [current]); const delta = capabilityDelta(manifests.v4, current); return <section className="workspace"><div className="bar"><div><p className="eyebrow">CANONICAL LIFECYCLE</p><span className="mode">DEMO FIXTURE — no live chain claim</span></div><div className="actions"><button onClick={() => setMode("v4")}>v4 sealed</button><button className="secondary" onClick={() => setMode("v41")}>v4.1 benign update</button><button className="secondary" onClick={() => setMode("v5")}>Simulate v5 mutation</button></div></div><div className="grid"><article className="panel"><p className="eyebrow">TOOL RECORD</p><h2>Mercury FX · v{current.version}</h2><p className="metadata">Digest {manifestDigest(current).slice(0, 18)}…{manifestDigest(current).slice(-8)}</p><div className="caps">{current.capabilities.map((cap) => <span className={`cap ${cap.severity === "CRITICAL" ? "danger" : ""}`} key={`${cap.name}${cap.target}`}>{cap.name} · {cap.target}</span>)}</div><p className="metadata">Registered payment destination: {current.payment.destination}</p></article><article className="panel"><p className="eyebrow">REFERENCE AGENT PRE-FLIGHT</p><h2>{decision.allowed ? "Invocation allowed" : "Invocation blocked"}</h2><div className={`status ${decision.allowed ? "allow" : "block"}`}>{decision.allowed ? "ALLOW" : "BLOCK"}</div><ul className="reasons">{decision.allowed ? <><li>SEAL_CURRENT</li><li>PRICE_WITHIN_CAP</li><li>DENY_RULES_SATISFIED</li></> : decision.reasons.map((reason) => <li key={reason}>{reason}</li>)}</ul><button disabled={!decision.allowed}>{decision.allowed ? "Settlement eligible: 0.02 Demo USDT" : "Payment not released"}</button></article></div><article className="panel delta"><p className="eyebrow">DETERMINISTIC CAPABILITY DELTA</p><strong className={delta.classification === "CRITICAL_EXPANSION" ? "critical" : ""}>{delta.classification}</strong><p className="metadata">{delta.added.length ? `Added: ${delta.added.map((cap) => cap.name).join(", ")}` : "Capability delta: none"}</p><p className="metadata">{decision.allowed ? "A changed digest needs reassessment before resealing." : "DENY_WALLET_SIGNING — no valid seal, no autonomous payment."}</p></article></section>; }
