import fs from "node:fs";
import path from "node:path";
import solc from "solc";
import { createPublicClient, createWalletClient, http, type Hex } from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { botTestnet } from "../lib/bot/chain";

const readEnv = () => Object.fromEntries(fs.readFileSync(".env.local", "utf8").split(/\r?\n/).filter((line) => line.includes("=") && !line.startsWith("#")).map((line) => { const index = line.indexOf("="); return [line.slice(0, index), line.slice(index + 1)]; }));
const env = readEnv(); const key = env.BOT_DEPLOYER_PRIVATE_KEY;
if (!key) throw new Error("BOT_DEPLOYER_PRIVATE_KEY is absent from .env.local. Configure it locally; never paste it into chat.");
const compile = () => { const root = process.cwd(); const sources = Object.fromEntries(fs.readdirSync("contracts/src").filter((name: string) => name.endsWith(".sol")).map((name: string) => [`contracts/src/${name}`, { content: fs.readFileSync(path.join("contracts/src", name), "utf8") }])); const output = JSON.parse(solc.compile(JSON.stringify({ language: "Solidity", sources, settings: { optimizer: { enabled: true, runs: 200 }, outputSelection: { "*": { "*": ["abi", "evm.bytecode.object"] } } } }), { import: (name: string) => { const file = path.join(root, "node_modules", name); return fs.existsSync(file) ? { contents: fs.readFileSync(file, "utf8") } : { error: `Missing ${name}` }; } })); const errors = (output.errors ?? []).filter((item: { severity: string }) => item.severity === "error"); if (errors.length) throw new Error(errors.map((item: { formattedMessage: string }) => item.formattedMessage).join("\n")); return output.contracts as Record<string, Record<string, { abi: unknown; evm: { bytecode: { object: string } } }>>; };
const artifact = (compiled: ReturnType<typeof compile>, file: string, name: string) => compiled[file][name];
async function deploy() { const account = privateKeyToAccount(key as Hex); const publicClient = createPublicClient({ chain: botTestnet, transport: http(env.BOT_RPC_URL || botTestnet.rpcUrls.default.http[0]) }); const walletClient = createWalletClient({ account, chain: botTestnet, transport: http(env.BOT_RPC_URL || botTestnet.rpcUrls.default.http[0]) }); const chainId = await publicClient.getChainId(); if (chainId !== 968) throw new Error(`Wrong chain: ${chainId}`); const balance = await publicClient.getBalance({ address: account.address }); if (balance === 0n) throw new Error(`Deployer ${account.address} has zero BOT Testnet balance. Fund it from https://faucet.botchain.ai/basic then retry.`); const contracts = compile(); const demo = artifact(contracts, "contracts/src/MockUSDT.sol", "MockUSDT"); const registry = artifact(contracts, "contracts/src/SkillSealRegistry.sol", "SkillSealRegistry"); const settlement = artifact(contracts, "contracts/src/SkillSealSettlement.sol", "SkillSealSettlement"); const deployOne = async (item: typeof demo, args: readonly unknown[]) => { const hash = await walletClient.deployContract({ abi: item.abi as [], bytecode: `0x${item.evm.bytecode.object}` as Hex, args: args as never }); const receipt = await publicClient.waitForTransactionReceipt({ hash }); if (!receipt.contractAddress) throw new Error("Missing contract address"); const code = await publicClient.getCode({ address: receipt.contractAddress }); if (!code || code === "0x") throw new Error("Bytecode verification failed"); return { address: receipt.contractAddress, deploymentTx: hash, block: receipt.blockNumber.toString() }; }; const demoDeployment = await deployOne(demo, [account.address, 10_000_000_000n]); const registryDeployment = await deployOne(registry, [account.address, account.address]); const settlementDeployment = await deployOne(settlement, [registryDeployment.address, demoDeployment.address]); fs.writeFileSync("deployments/bot-testnet.json", JSON.stringify({ chainId, deployer: account.address, token: demoDeployment, registry: registryDeployment, settlement: settlementDeployment }, null, 2)); console.log(JSON.stringify({ demoDeployment, registryDeployment, settlementDeployment }, null, 2)); }
deploy().catch((error: unknown) => { console.error(error instanceof Error ? error.message : "Deployment failed"); process.exitCode = 1; });
