import { getAddress, isAddress, keccak256, stringToHex } from "viem";
import type { Capability, CapabilityManifest, Mandate, PolicyDecision, PolicyReason, Seal, Invocation, Risk } from "./types";

const rank: Record<Risk, number> = { LOW: 1, MEDIUM: 2, HIGH: 3, CRITICAL: 4, UNKNOWN: 5 };
const critical = new Set(["WALLET_SIGN_TRANSACTION", "WALLET_SEND_TRANSACTION", "TOKEN_TRANSFER", "SECRET_EXPORT", "SHELL_EXECUTION", "ARBITRARY_CODE_EXECUTION"]);
const stable = (value: unknown): string => { if (Array.isArray(value)) return `[${value.map(stable).join(",")}]`; if (value && typeof value === "object") { const record = value as Record<string, unknown>; return `{${Object.keys(record).sort().map((key) => `${JSON.stringify(key)}:${stable(record[key])}`).join(",")}}`; } return JSON.stringify(value); };
export const canonicalizeManifest = (manifest: CapabilityManifest) => stable({ ...manifest, operator: isAddress(manifest.operator) ? getAddress(manifest.operator).toLowerCase() : manifest.operator, payment: { ...manifest.payment, destination: isAddress(manifest.payment.destination) ? getAddress(manifest.payment.destination).toLowerCase() : manifest.payment.destination }, capabilities: [...manifest.capabilities].sort((a, b) => key(a).localeCompare(key(b))) });
export const manifestDigest = (manifest: CapabilityManifest): `0x${string}` => keccak256(stringToHex(canonicalizeManifest(manifest)));
const key = (capability: Capability) => `${capability.name}|${capability.scope}|${capability.target}`;
export const capabilityDelta = (before: CapabilityManifest, after: CapabilityManifest) => { const left = new Map(before.capabilities.map((item) => [key(item), item])); const right = new Map(after.capabilities.map((item) => [key(item), item])); const added = [...right.entries()].filter(([id]) => !left.has(id)).map(([, item]) => item); const removed = [...left.entries()].filter(([id]) => !right.has(id)).map(([, item]) => item); const paymentChanged = before.payment.destination.toLowerCase() !== after.payment.destination.toLowerCase(); const priceIncreased = BigInt(after.payment.maxAmountBaseUnits) > BigInt(before.payment.maxAmountBaseUnits); const reasons = [...added.filter((item) => critical.has(item.name)).map((item) => `${item.name}_ADDED`), ...(paymentChanged ? ["PAYMENT_DESTINATION_CHANGED"] : []), ...(priceIncreased ? ["PAYMENT_LIMIT_INCREASED"] : [])]; return { added, removed, paymentChanged, priceIncreased, reasons, classification: reasons.length ? (reasons.some((reason) => reason.includes("WALLET") || reason.includes("DESTINATION")) ? "CRITICAL_EXPANSION" : "EXPANDED") : added.length || removed.length ? "EQUIVALENT" : "NONE" } as const; };
export const evaluateMandate = ({ mandate, manifest, seal, invocation, spentTodayBaseUnits = 0n }: { mandate: Mandate; manifest: CapabilityManifest; seal?: Seal; invocation: Invocation; spentTodayBaseUnits?: bigint }): PolicyDecision => { const reasons: PolicyReason[] = []; const digest = manifestDigest(manifest); if (!seal) reasons.push("SEAL_MISSING"); else { if (seal.manifestDigest !== digest || seal.version !== manifest.version) reasons.push("SEAL_STALE", "MANIFEST_CHANGED"); if (seal.revoked || Date.parse(seal.expiresAt) <= Date.now()) reasons.push("ASSESSMENT_EXPIRED"); if (rank[seal.risk] > rank[mandate.maxRisk]) reasons.push("RISK_TOO_HIGH"); } const names = manifest.capabilities.map((capability) => capability.name); if (names.some((name) => mandate.deniedCapabilities.includes(name)) || names.some((name) => !mandate.allowedCapabilities.includes(name))) reasons.push("CAPABILITY_DENIED"); if (manifest.capabilities.some((capability) => capability.target !== "*" && !mandate.allowedDomains.includes(capability.target))) reasons.push("DOMAIN_NOT_ALLOWED"); const amount = BigInt(invocation.amountBaseUnits); if (amount > BigInt(mandate.maxPerInvocationBaseUnits) || amount > BigInt(manifest.payment.maxAmountBaseUnits)) reasons.push("PRICE_TOO_HIGH"); if (amount + spentTodayBaseUnits > BigInt(mandate.maxPerDayBaseUnits)) reasons.push("DAILY_LIMIT_EXCEEDED"); if (invocation.recipient.toLowerCase() !== manifest.payment.destination.toLowerCase()) reasons.push("PAYMENT_DESTINATION_CHANGED"); return { allowed: reasons.length === 0, reasons: [...new Set(reasons)], manifestDigest: digest }; };
